const data = [
    {
        "step": "Call NetJets and renew subscription.",
        "order": "1001",
        "url": "http://www.google.com",
        "assigned": "RFA",
        "note": "This is my note.",
        "isComplete": "false",
    },
    {
        "step": "Sell LEAPS against the Market",
        "order": "1002",
        "url": "http://www.google.com",
        "assigned": "RFA",
        "note": "This is my note.",
        "isComplete": "false",
    },
    {
        "step": "Create Project Plan for next billion $ idea.",
        "order": "1003",
        "url": "http://www.google.com",
        "assigned": "RFA",
        "note": "This is my note.",
        "isComplete": "false",
    },
    {
        "step": "Get reservation at The Four Seasons Maui Resort for 2 weeks.",
        "order": "1004",
        "url": "http://www.google.com",
        "assigned": "RFA",
        "note": "This is my note.",
        "isComplete": "false",
    },
    {
        "step": "Schedule Travel Maui",
        "order": "1005",
        "url": "http://www.google.com",
        "assigned": "RFA",
        "note": "This is my note.",
        "isComplete": "false",
    },
    {
        "step": "Get test drive/ride for 2021 Audi S8",
        "order": "1006",
        "url": "http://www.google.com",
        "assigned": "RFA",
        "note": "This is my note.",
        "isComplete": "false",
    }
]